### ISSUE TITLE
Fix: Rename

### ISSUE THREAD

**Issue by Walimouche** [Server-Analytics/languages#5]
You should update these files ''fr.js'', ''en.js'', ''de.js'' to fr-FR.js, en-US.js, de-DE.js to follow i18n conventions and to be more intuitive

**Comment by UBrainDev** [comment]
Sure, this is a good idea, I will work on this (as the client uses the file names instead of the `infos.language_code` propriety). Thanks!

**Comment by Bouse2Vache** [comment]
So there won't be that in V3? 😭
@UBrainDev
